#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'

echo
echo "Welcome to ${GREEN}FRIED FISH"
echo
echo "${YELLOw}WARNING!! This script removes the ~/.config and the ~/.local directories"

read -p"Would you like to proceed? [y/n] " -n 1 -r 
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
        cd ~
        rm -rf .config
        rm -rf .local
        git clone https://github.com/jcristol/.config
        cd .config
        source ./install
        cd ~
fi
