#!/bin/bash


echo "installing a dope config"
echo "WARNING!! This script removes the ~/.config and the ~/.local directories"

read -p"Would you like to proceed? [y/n] " -n 1 -r 
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
        cd ~
        rm -rf .config
        rm -rf .local
        git clone https://github.com/jcristol/.config
        cd .config
        source ./install
        cd ~
fi
