#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'

echo "${GREEN}Installing brew and brew packages\n"
brew install bat
brew install exa
brew install fish
brew install neovim
brew install watchman

echo "${GREEN}Installing nvm\n"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

echo "${GREEN}Installing fisher the fish package manager\n"
fish -c "curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish"

echo "${GREEN}Installing useful fish plugins\n"
fish -c "fisher add edc/bass"
fish -c "fisher add FabioAntunes/fish-nvm"
fish -c "fisher add jethrokuan/z"
fish -c "fisher add laughedelic/fish_logo"
fish -c "fisher add oh-my-fish/theme-default"
fish -c "fisher add cbsghost/fish-legacycolor"
fish -c "cat fish_functions | python ~/.config/function_scribe.py | fish"

echo "${GREEN}Installing node using fnvm\n"
fish -c "nvm install node"

echo "${GREEN}Chaning the default shell will need your password twice\n"
chsh -s /usr/local/bin/fish
echo /usr/local/bin/fish | sudo tee -a /etc/shells

echo "${GREEN}Install oh my fish for a dope theme\n"
fish -c "curl -L https://get.oh-my.fish | fish"
