#!/bin/bash

brew install bat
brew install exa
brew install fish
brew install neovim
brew install watchman

# install nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

# install fisher
fish -c "curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish"

# run these commands
fish -c "fisher add edc/bass"
fish -c "fisher add FabioAntunes/fish-nvm"
fish -c "fisher add jethrokuan/z"
fish -c "fisher add laughedelic/fish_logo"
fish -c "fisher add oh-my-fish/theme-default"
fish -c "fisher add cbsghost/fish-legacycolor"
fish -c "cat fish_functions | python function_scribe.py | fish"

# install node
fish -c "nvm install node"

# install oh my fish
fish -c "curl -L https://get.oh-my.fish | fish"
