#!/bin/bash

echo "installing a dope config"
echo "WARNING!! This script removes the ~/.config directory"

read -p "Would you like to proceed? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  cd ~
  rm -irf .config
  git clone https://github.com/jcristol/.config
  
  brew install bat
  brew install exa
  brew install fish
  brew install neovim
  brew install watchman

  # install nvm
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

  # install fisher
  fish -c "curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish"

  # run these commands
  fish -c "fisher add edc/bass"
  fish -c "fisher add FabioAntunes/fish-nvm"
  fish -c "fisher add jethrokuan/z"
  fish -c "fisher add laughedelic/fish_logo"
  fish -c "fisher add oh-my-fish/theme-default"
  fish -c "fisher add cbsghost/fish-legacycolor"
  fish -c "cat fish_functions | python ~/.config/function_scribe.py | fish"

  # install node
  fish -c "nvm install node"

  # install oh my fish
  fish -c "curl -L https://get.oh-my.fish | fish"

  # change default shell to fish
  chsh -s /usr/local/bin/fish
  echo /usr/local/bin/fish | sudo tee -a /etc/shells
fi
